general {
    layout = dwindle
    gaps_in = 4
    gaps_out = 6
    border_size = 2
   col.active_border = rgba(505359FF)
  col.inactive_border = rgba(000000FF)
}

decoration {
    rounding = 0
    dim_special = 0.4
    active_opacity = 1.00
    inactive_opacity = 1.00
}

layerrule {
  name = layerrule-1
  ignore_alpha = 0.1
  match:namespace = notifications
}

gestures {
    gesture = 3, left, dispatcher, workspace, -1 
    gesture = 3, right, dispatcher, workspace, +1
    gesture = 4, up, dispatcher, togglefloating
}
